# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['speak.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('cmudict-0.7b-ipa.txt', '.'),
        
    ],
    hiddenimports=[
        'pyttsx3.drivers',
        'pyttsx3.drivers.sapi5',
        'pyttsx3.drivers.nsss',
        'pyttsx3.drivers.espeak',
        'pystray._util_win32',
        'PIL._tkinter_finder',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'eng_to_ipa',
        'pyperclip',
        'threading',
        'time',
        're',
        'json',
        'pathlib',
        'urllib.request',
        'requests',
        'pystray',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'socket',
        'psutil',
        'subprocess',
        'tempfile',
        'platform',
        'pkg_resources',
        'setuptools',
        'distutils',
        'encodings',
        'codecs',
        'locale',
        'os',
        'sys',
        'gc',
    ],
    hookspath=['.'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'multiprocessing',
        'concurrent.futures',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='TTS_Pronunciation_Practice',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    
)
